import type { VideoRecord } from "./types";

export const demoVideos: VideoRecord[] = [
  {
    id: "demo-ai-coding",
    platform: "bilibili",
    sourceUrl: "https://www.bilibili.com/",
    mediaType: "视频",
    title: "普通人如何用 AI 编程完成第一个真实项目",
    author: "示例创作者",
    duration: 754,
    status: "complete",
    statusText: "字幕完整",
    summary:
      "视频用一个小项目说明 AI 编程的入门路径，重点是缩小任务、即时验证，以及始终保留人工判断。",
    tags: ["AI 编程", "入门", "项目实践"],
    userTags: ["稍后实践"],
    primaryCategory: "AI 与工具",
    secondaryCategory: "AI 编程",
    sparkNote: "这个方法可以用来改进下一个 Codex 项目的任务拆分。",
    sparkCreatedAt: "收藏于今天 14:18",
    updatedAt: "今天 14:20",
    integrity: "视频明确提到",
    subtitleSource: "公开字幕",
    outline: [
      { id: "why", title: "为什么从小项目开始", start: 42, end: 181 },
      { id: "how", title: "与 AI 协作的四个步骤", start: 205, end: 468 },
      { id: "risk", title: "验证结果与常见误区", start: 489, end: 692 },
    ],
    points: [
      {
        id: "point-1",
        title: "先把目标缩小到一个可验证结果",
        body: "不要从完整产品开始。先选择可以在一到两小时内看到结果的小任务，再决定是否继续扩大范围。",
        evidenceIds: ["ev-1"],
        kind: "point",
      },
      {
        id: "step-1",
        title: "写清输入、输出和验收条件",
        body: "把模糊想法改成具体任务，说明输入是什么、输出长什么样，以及怎样判断已经完成。",
        evidenceIds: ["ev-2"],
        kind: "step",
      },
      {
        id: "step-2",
        title: "每完成一小步就运行验证",
        body: "不要连续生成大量代码后再测试。每次只改一个目标，并立刻运行或检查结果。",
        evidenceIds: ["ev-3"],
        kind: "step",
      },
      {
        id: "risk-1",
        title: "不要把能运行等同于结果正确",
        body: "模型可能生成表面可用但边界条件错误的实现。关键数据、权限和删除操作仍需人工检查。",
        evidenceIds: ["ev-4"],
        kind: "risk",
      },
    ],
    evidence: [
      {
        id: "ev-1",
        start: 62,
        end: 91,
        text: "如果你第一次就想做一个完整产品，通常很快会卡住。先选一个一两个小时能看到结果的小项目。",
      },
      {
        id: "ev-2",
        start: 205,
        end: 244,
        text: "你要先告诉工具输入是什么，最后想得到什么，还要把你怎么判断它完成了写清楚。",
      },
      {
        id: "ev-3",
        start: 325,
        end: 357,
        text: "每完成一小步马上运行，不要等它一次写完几百行以后才第一次打开。",
      },
      {
        id: "ev-4",
        start: 548,
        end: 594,
        text: "能跑不代表是对的，特别是涉及数据、权限和删除的时候，你自己一定要再检查一次。",
      },
    ],
    notes: [
      {
        id: "note-1",
        pointId: "step-1",
        targetKey: "step-1",
        text: "可以复用到下一个 Codex 任务的验收描述中。",
        targetType: "step",
        author: "我",
        createdAt: "今天 14:22",
        updatedAt: "今天 14:22",
      },
    ],
    questions: [],
  },
  {
    id: "demo-growth",
    platform: "douyin",
    sourceUrl: "https://www.douyin.com/",
    mediaType: "视频",
    title: "做内容之前先想清楚谁会因为哪一个问题找到你",
    author: "示例创作者",
    duration: 286,
    status: "warning",
    statusText: "字幕有缺口",
    summary:
      "视频围绕内容获客提出一个核心判断：先确定目标用户正在主动搜索的问题，再决定选题和表达方式。",
    tags: ["内容获客", "选题"],
    userTags: [],
    primaryCategory: "创作参考",
    secondaryCategory: "内容获客",
    sparkNote: "以后写选题时，先回来核对目标用户正在搜什么。",
    sparkCreatedAt: "收藏于昨天 18:40",
    updatedAt: "昨天 18:45",
    integrity: "根据现有字幕归纳",
    subtitleSource: "ASR 字幕",
    outline: [
      { id: "audience", title: "先定义谁会来找你", start: 12, end: 88 },
      { id: "topic", title: "从真实问题生成选题", start: 101, end: 223 },
    ],
    points: [],
    evidence: [],
    notes: [],
    questions: [],
  },
  {
    id: "demo-processing",
    platform: "local",
    sourceUrl: null,
    mediaType: "音频",
    title: "产品需求访谈录音 07-28",
    author: "本地上传",
    duration: 0,
    status: "processing",
    statusText: "AI 解析中",
    summary: "正在生成字幕并整理内容，已完成媒体检查。",
    tags: ["访谈"],
    userTags: [],
    primaryCategory: "知识与观点",
    secondaryCategory: "用户访谈",
    sparkNote: "重点找出用户为什么不愿意看完整视频。",
    sparkCreatedAt: "收藏于刚刚",
    updatedAt: "刚刚",
    integrity: "暂不可判断",
    subtitleSource: "正在生成",
    outline: [],
    points: [],
    evidence: [],
    notes: [],
    questions: [],
  },
  {
    id: "demo-missing",
    platform: "bilibili",
    sourceUrl: null,
    mediaType: "视频",
    title: "只有标题和简介的受限视频示例",
    author: "示例来源",
    duration: 0,
    status: "missing",
    statusText: "字幕缺失",
    summary: "未获得完整字幕，当前不能把标题和简介作为视频正文进行总结。",
    tags: ["待补充"],
    userTags: [],
    primaryCategory: "暂未分类",
    secondaryCategory: null,
    sparkNote: null,
    sparkCreatedAt: null,
    updatedAt: "7 月 26 日",
    integrity: "字幕残缺，无法判断",
    subtitleSource: "无字幕",
    outline: [],
    points: [],
    evidence: [],
    notes: [],
    questions: [],
  },
];
